### ISSUE TITLE
make branding changes for the pixelcorp.nl demo

### ISSUE THREAD

**Issue by Obult** [pixelcorp-nl/canvas.edu#1]
update

- [x] title (of page is currently Codam - Project description)
- [x] information endpoint is still pixels.codam.nl
- [x] update the hover effect on text, currently it blurs the text when moving pointer
- [x] remove Leon from major contributors list at the bottom

**Comment by LithiumOx** [comment]
@W2Wizard GTFO babe <3

**Comment by W2Wizard** [comment]
Im going to break bad jessy.
My name stays there buddy.

**Comment by Obult** [comment]
@W2Wizard This comment almost doubles your contibutions :P

**Comment by LithiumOx** [comment]
Shots fired
